### ISSUE TITLE
v1 milestone

### ISSUE THREAD

**Issue by coco98** [GavinRay97/hasura-data-dictionary#1]
- [x] Detailed 1st and 2nd degree diagrams on model page
- [x] Role selector
- [x] Add explorer to GraphiQL
- [x] Basic styling improvements (esp for visualization)
- [x] GraphQL schema search component and GraphQL field page

- [x] Plan on integrating remote schemas & actions? Will their relationships work? Will they show up on the model page?
- [ ] Let's set up a demo with the GraphQL API that powers Hasura cloud / lux
- [ ] Usage docs
- [ ] Demo app

**Comment by GavinRay97** [comment]
- Usage docs
  - Readme, usage instructions, architecture, etc.

- Add more comments to the Chinook tables/columns so they show up

Prior comment on visualization:
---

On the "Data Graph" page:
1. Predicatable / repeatable layouts that don’t change if the user refreshes the page
2. Small UX things (like a loading)
3. Unconnected nodes show up in a stack on the left / right?

On the detail diagram view:
1. A larger viewport that adjusts based on the size of the diagram
2. A label on the edge that tells me if it is an array or an object relationship
3. Hovering on the edge highlights the column names that are used in the relationship
